#@ load("@ytt:data", "data")
apiVersion: v1
kind: Namespace
metadata:
  name: sock-order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sock-order
  name: sock-order
  labels:
    app: sock-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sock-order
  template:
    metadata:
      labels:
        app: sock-order
    spec:
      containers:
      - name: sock-order
        image: 698489875176.dkr.ecr.ap-southeast-1.amazonaws.com/spring-socks-order
        env:
        - name: SOCK_CARTURL
          value: http://sock-cart.sock-cart.svc.cluster.local:8080
        - name: SOCK_PAYMENTURL
          value: http://sock-payment.sock-payment.svc.cluster.local:8080
        - name: SOCK_SHIPPINGURL
          value: http://sock-shipping.sock-shipping.svc.cluster.local:8080
        - name: SOCK_USERURL
          value: http://sock-user.sock-user.svc.cluster.local:8080
        - name: SIMPLE_DNS_DEFAULTPORTS_HTTP
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_TOMCAT_THREADS_MAX
          value: "4"
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
        - name: BPL_JVM_THREAD_COUNT
          value: "20"
        - name: BPL_JVM_HEAD_ROOM
          value: "5"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
          value: #@ data.values.sock_issuer_url or "http://sock-user.sock-user.svc.cluster.local:8080/oauth/token"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:p6spy:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: sock-order-mysql-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sock-order-mysql-secret
              key: password
        - name: MYSQL_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: sock-order-mysql-secret
              key: hostname
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: sock-order-mysql-secret
              key: port
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sock-order-mysql-secret
              key: database
        - name: INFO_JAVA_VERSION
          value: ${java.runtime.version}
        - name: INFO_JAVA_VENDOR
          value: ${java.vm.vendor}
        - name: LOGGING_EXCEPTIONCONVERSIONWORD
          value: "\t%replace(%replace(%xEx){'\n','\r'}){'\t','    '}%nopex"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m){'\n','\r'}${logging.exception-conversion-word:%wEx}%n"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 384Mi
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: sock-order
  name: sock-order
  labels:
    app: sock-order
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sock-order
  type: ClusterIP
  clusterIP: None