#@data/values
---
mysql_hostname: sock-order-mysql.sock-order.svc.cluster.local
mysql_port: "3306"
mysql_username: sockshop
mysql_password: sockshop
mysql_database: order-db
sock_issuer_url:
wavefront_uri: https://try.wavefront.com/
wavefront_api_token: efee3e2d-509f-4841-811c-c09613c0a048
wavefront_application_name: spring-socks