#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "fluent-bit-config"}})
---
data:
  #@overlay/replace via=lambda a, b: a + b.replace("\n", "\n    ")
  filter-kubernetes.conf: |-

        Labels              Off
        Annotations         Off

  #@overlay/replace via=lambda a, b: a + b
  filter-record.conf: |-

    [FILTER]
        Name parser
        Match kube.*
        Key_Name message
        Parser envoy
        Preserve_Key True
        Reserve_Data True