#@ load("@ytt:data", "data")
apiVersion: v1
kind: Namespace
metadata:
  name: sock-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sock-ui
  name: sock-ui
  labels:
    app: sock-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sock-ui
  template:
    metadata:
      labels:
        app: sock-ui
    spec:
      containers:
      - name: sock-ui
        image: 698489875176.dkr.ecr.ap-southeast-1.amazonaws.com/spring-socks-ui
        env:
        - name: SOCK_CATALOGURL
          value: http://sock-catalog.sock-catalog.svc.cluster.local:8080
        - name: SOCK_CARTURL
          value: http://sock-cart.sock-cart.svc.cluster.local:8080
        - name: SOCK_ORDERURL
          value: http://sock-order.sock-order.svc.cluster.local:8080
        - name: SOCK_PAYMENTURL
          value: http://sock-payment.sock-payment.svc.cluster.local:8080
        - name: SOCK_SHIPPINGURL
          value: http://sock-shipping.sock-shipping.svc.cluster.local:8080
        - name: SOCK_USERURL
          value: #@ "/".join(data.values.sock_issuer_url.split("/")[0:3]) if data.values.sock_issuer_url else "http://sock-user.sock-user.svc.cluster.local:8080"
        - name: SIMPLE_DNS_DEFAULTPORTS_HTTP
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_TOMCAT_THREADS_MAX
          value: "4"
        - name: JAVA_TOOL_OPTIONS
          value: -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo
        - name: BPL_JVM_THREAD_COUNT
          value: "20"
        - name: BPL_JVM_HEAD_ROOM
          value: "5"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_UI_AUTHORIZATIONURI
          value: #@ "{}/oauth/authorize".format(data.values.sock_user_external_url)
        - name: INFO_JAVA_VERSION
          value: ${java.runtime.version}
        - name: INFO_JAVA_VENDOR
          value: ${java.vm.vendor}
        - name: LOGGING_EXCEPTIONCONVERSIONWORD
          value: "\t%replace(%replace(%xEx){'\n','\r'}){'\t','    '}%nopex"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m){'\n','\r'}${logging.exception-conversion-word:%wEx}%n"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 384Mi
        readinessProbe:
          httpGet:
            path: /management/health/readiness
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /management/health/liveness
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: sock-ui
  name: sock-ui
  labels:
    app: sock-ui
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sock-ui
  type: LoadBalancer